#!/usr/bin/env python3
"""Generate deterministic rule adapters from the canonical Dopamine skill."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "skills/dopamine/SKILL.md"
NOTICE = "<!-- Generated by scripts/generate_integrations.py; edit skills/dopamine/SKILL.md instead. -->\n\n"


def skill_body() -> str:
    text = SKILL.read_text(encoding="utf-8")
    parts = text.split("---\n", 2)
    if len(parts) != 3 or parts[0]:
        raise ValueError("skills/dopamine/SKILL.md has invalid frontmatter")
    body = parts[2]
    return body.replace(
        "Choose the smallest decisive check from [references/verification.md](references/verification.md).",
        "Choose the smallest decisive executable check appropriate to the artifact.",
    )


def outputs() -> dict[Path, str]:
    body = skill_body()
    plain = NOTICE + body
    canonical_skill = SKILL.read_text(encoding="utf-8")
    verification = (SKILL.parent / "references/verification.md").read_text(encoding="utf-8")
    return {
        ROOT / "AGENTS.md": plain,
        ROOT / ".agents/rules/dopamine.md": plain,
        ROOT / ".clinerules/dopamine.md": plain,
        ROOT / ".github/copilot-instructions.md": plain,
        ROOT / ".qoder/rules/dopamine.md": plain,
        ROOT / ".cursor/rules/dopamine.mdc": (
            "---\n"
            "description: Dopamine selects the smallest verified solution with adaptive effort.\n"
            "globs:\n"
            "alwaysApply: true\n"
            "---\n\n" + NOTICE + body
        ),
        ROOT / ".windsurf/rules/dopamine.md": (
            "---\ntrigger: always_on\n---\n\n" + NOTICE + body
        ),
        ROOT / ".kiro/steering/dopamine.md": (
            "---\ninclusion: always\n---\n\n" + NOTICE + body
        ),
        ROOT / ".opencode/skills/dopamine/SKILL.md": canonical_skill,
        ROOT / ".opencode/skills/dopamine/references/verification.md": verification,
        ROOT / ".openclaw/skills/dopamine/SKILL.md": canonical_skill,
        ROOT / ".openclaw/skills/dopamine/references/verification.md": verification,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    stale: list[str] = []
    for path, expected in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"generated {path.relative_to(ROOT)}")
    if stale:
        print("stale generated integrations: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
